cadastrocolaboradores.colaboradorjaexistentecpf=Colaborador j\u00E1 existente com este CPF.
cadastrocolaboradores.colaboradornaoencontrado=Colaborador n\u00E3o encontrado com este CPF.
cadastrocolaboradores.colaboradorcadastradocomsucesso=Colaborador cadastrado com sucesso.
comum.cpfinvalido=CPF inv\u00E1lido.
cadastrocolaboradores.baseobrigatorio=Campo Base obrigat\u00F3rio.
cadastrocolaboradores.nomeobrigatorio=Campo Nome obrigat\u00F3rio.
cadastrocolaboradores.datanascimentoobrigatorio=Campo Data de nascimento obrigat\u00F3rio.
cadastrocolaboradores.cpfobrigatorio=Campo CPF obrigat\u00F3rio.
cadastrocolaboradores.datanascimentoinvalida=Data de nascimento inv\u00E1lida.
comum.formato_data=dd/MM/yyyy
